# dataset
train_dataset:
  data_loader:
    type: CommonDataLoader
    shuffle: False
    split: "train"
    load_func: "load_from_disk"
    path: /path/to/handled_data # 预处理后数据集的路径
    packing: pack
    handler:
      - type: PackingHandler
        seq_length: 32768
        pad_token: 151643
        output_columns: ["input_ids", "labels", "actual_seq_len"]
    adaptor_config:
      compress_mask: False
